services:
  video_ingestion:
    build: {context: ., dockerfile: video_ingestion/Dockerfile}
    network_mode: host
    env_file: .env
    restart: always
  motion_detection:
    build: {context: ., dockerfile: motion_detection/Dockerfile}
    network_mode: host
    env_file: .env
    restart: always
    depends_on: [video_ingestion]
